name: 'Install Clojure CLI'
description: 'Install the latest Clojure CLI for Linux'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        curl -O https://download.clojure.org/install/linux-install-1.10.3.855.sh
        chmod +x linux-install-1.10.3.855.sh
        sudo ./linux-install-1.10.3.855.sh
